version: '3.2'
services:
  {{PROJECT_NAME}}-dev-env:
    container_name: '{{PROJECT_NAME}}-dev-env'
    build:
        context: .
    stdin_open: true
    tty: true
    volumes:
      - ../..:/code
    working_dir: /code
